version: "3"
services:
  db:
    image: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
    ports:
      - "27018:27017" # off the standard port to avoid conflicts
    volumes:
      - ./mongodata:/data/db
  api:
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "3000:3000"
    env_file:
      - active.env
    depends_on:
      - db
    links:
      - db
